resource_types:
  - name: git-branch-heads
    type: docker-image
    source:
      repository: vito/git-branch-heads-resource

resources:
   - name: CheckingBranches
     type: git-branch-heads
     source:
       uri: git@github.com:ThaKangBaby/ConcourseTest.git
       branch: [ready/*]
       private_key: {{private_key}}
       git_config:
       - name: core.bigFileThreshold
         value: 10m
   - name: ConcourseTest
     type: git
     source:
       uri: git@github.com:ThaKangBaby/ConcourseTest.git
       branch: master
       private_key: {{private_key}}
       git_config:
       - name: core.bigFileThreshold
         value: 10m
  #  - name: fetch-ready-branches
  #    type: time
  #    source:
  #      interval: 10s

jobs:
- name: Check-Ready-Branch
  plan:
  - get: CheckingBranches
    trigger: false
  - get: ConcourseTest
    trigger: true
  # - get: fetch-ready-branches
  #   trigger: true
  - task: Check-ready-branches
    file: ConcourseTest/ci/tasks/ready-integration.yml
    # params:
    #   volumes: ["/root/.ssh:/root/.ssh"]
  - put: ConcourseTest
    params: {repository: integration}
  # - task: job-integration
  #   file: ConcourseTest/ci/tasks/job-integration.yml


# - name: Output-Ready-Branch
#   plan:
#   - get: ConcourseTest
  #   passed: [Check-Ready-Branch]
  #   trigger: true
  # - task: job-integration
  #   file: ConcourseTest/ci/tasks/job-integration.yml



    # config:
    #   platform: linux
    #   image_resource:
    #     type: docker-image
    #     source: {repository: thakangbaby/javabox, tag: "v1.1"}
    #   outputs:
    #   - name: testfolder
    #   run:
    #     path: sh
    #     args:
    #     - -exec
    #     - |
    #       touch testfolder/hi
    #       ls -la
    #       ls testfolder/

  #- put: ConcourseTest
