resource_types:
  - name: git-branch-heads
    type: docker-image
    source:
      repository: vito/git-branch-heads-resource
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource

resources:
   - name: CheckingBranches
     type: git-branch-heads
     source:
       uri: git@github.com:ThaKangBaby/ConcourseTest.git
       branch: [ready/*]
       private_key: {{private_key}}
       git_config:
       - name: core.bigFileThreshold
         value: 10m
   - name: Praqma.com
     type: git
     source:
       uri: git@github.com:ThaKangBaby/praqma.com.git
       branch: gh-pages
       private_key: {{private_key}}
       git_config:
       - name: core.bigFileThreshold
         value: 10m
   - name: send-an-email
     type: email
     source:
       smtp:
         host: {{smtp-host}}
         port: {{smtp-port}}
         username: {{smtp-username}}
         password: {{smtp-password}}
       from: {{email-from}}
       to: [ {{email-to}} ]

jobs:
- name: Check-Ready-Branch
  plan:
  - get: CheckingBranches
    trigger: true
  - get: Praqma.com
    trigger: false
  - task: Check-ready-branches
    file: CheckingBranches/ci/tasks/buildtest.yml
    params:
      token: {{token}}
      output_subject_file: integration/results.txt
      output_body_file: integration/results.txt
  - put: send-an-email
    params:
      subject: integration/results.txt
      body: integration/results.txt
