resource_types:
  - name: git-branch-heads
    type: docker-image
    source:
      repository: vito/git-branch-heads-resource

resources:
   - name: CheckingBranches
     type: git-branch-heads
     source:
       uri: git@github.com:ThaKangBaby/ConcourseTest.git
       branch: [ready/*]
       private_key: {{private_key}}
       git_config:
       - name: core.bigFileThreshold
         value: 10m
   - name: ConcourseTest
     type: git
     source:
       uri: git@github.com:ThaKangBaby/ConcourseTest.git
       branch: master
       private_key: {{private_key}}
       git_config:
       - name: core.bigFileThreshold
         value: 10m
  #  - name: fetch-ready-branches
  #    type: time
  #    source:
  #      interval: 10s

jobs:
- name: Check-Ready-Branch
  plan:
  - get: CheckingBranches
    trigger: false
  - get: ConcourseTest
    trigger: true
  - task: Check-ready-branches
    file: ConcourseTest/ci/tasks/buildtest.yml
  # - put: ConcourseTest
  #   params: {repository: integration}
  # - task: job-integration
  #   file: ConcourseTest/ci/tasks/job-integration.yml
