resource_types:
  - name: git-branch-heads
    type: docker-image
    source:
      repository: vito/git-branch-heads-resource


resources:
   - name: CheckingBranches
     type: git-branch-heads
     source:
       uri: git@github.com:ThaKangBaby/ConcourseTest.git
       branch: [ready/*]
       private_key: {{private_key}}
       git_config:
       - name: core.bigFileThreshold
         value: 10m
   - name: Praqma.com
     type: git-branch-heads
     source:
       uri: git@github.com:ThaKangBaby/praqma.com.git
       branch: [ready/*]
       private_key: {{private_key}}
       git_config:
       - name: core.bigFileThreshold
         value: 10m
   - name: slack-alert
     type: slack-notification
     source:
      url: https://hooks.slack.com/services/XXXX
   - name: stuff
     mykey: foobar
  #  - name: fetch-ready-branches
  #    type: time
  #    source:
  #      interval: 10s

jobs:
- name: Check-Ready-Branch
  plan:
  - get: CheckingBranches
    trigger: true
    private_key: {{private_key}}
  - get: Praqma.com
    trigger: false
  - get: stuff
  - task: Check-ready-branches
    file: CheckingBranches/ci/tasks/buildtest.yml
    params:
      private_key: {{private_key}}
      foo: taskparam
  - put: slack-alert
    params:
      always_notify: true
      username: Concourse
      channel: '#my_channel'
      text_file: integration/results.txt

  # - put: ConcourseTest
  #   params: {repository: integration}
  # - task: job-integration
  #   file: ConcourseTest/ci/tasks/job-integration.yml
