resource_types:
  - name: git-branch-heads
    type: docker-image
    source:
      repository: vito/git-branch-heads-resource
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
   - name: CheckingBranches
     type: git-branch-heads
     source:
       uri: git@github.com:ThaKangBaby/ConcourseTest.git
       branch: [ready/*]
       private_key: {{private_key}}
       git_config:
       - name: core.bigFileThreshold
         value: 10m
   - name: Praqma.com
     type: git
     source:
       uri: git@github.com:ThaKangBaby/praqma.com.git
       branch: gh-pages
       private_key: {{private_key}}
       git_config:
       - name: core.bigFileThreshold
         value: 10m
   - name: slack-alert
     type: slack-notification
     source:
      url: https://hooks.slack.com/services/XXXX

  #  - name: fetch-ready-branches
  #    type: time
  #    source:
  #      interval: 10s

jobs:
- name: Check-Ready-Branch
  plan:
  - get: CheckingBranches
    trigger: true
    params:
      token: {{token}}
  - get: Praqma.com
    trigger: false
  - task: Check-ready-branches
    file: CheckingBranches/ci/tasks/buildtest.yml
  - put: slack-alert
    params:
      always_notify: true
      username: Concourse
      channel: '#my_channel'
      text_file: integration/results.txt

  # - put: ConcourseTest
  #   params: {repository: integration}
  # - task: job-integration
  #   file: ConcourseTest/ci/tasks/job-integration.yml
