resource_types:
  - name: git-branch-heads
    type: docker-image
    source:
      repository: vito/git-branch-heads-resource
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
   - name: CheckingBranches
     type: git-branch-heads
     source:
       uri: git@github.com:ThaKangBaby/ConcourseTest.git
       branch: [ready/*]
       private_key: {{private_key}}
       git_config:
       - name: core.bigFileThreshold
         value: 10m
   - name: Praqma.com
     type: git
     source:
       uri: git@github.com:ThaKangBaby/praqma.com.git
       branch: gh-pages
       private_key: {{private_key}}
       git_config:
       - name: core.bigFileThreshold
         value: 10m
   - name: slack-alert
     type: slack-notification
     source:
       url: {{slack-hook}}

jobs:
- name: Check-Ready-Branch
  plan:
  - get: CheckingBranches
    trigger: true
  - get: Praqma.com
    trigger: false
  - task: Check-ready-branches
    file: CheckingBranches/ci/tasks/buildtest.yml
    params:
      token: {{token}}
    on_failure:
      put: slack-alert
      params:
        channel: '#concoursebuildresults'
        # text: |
          Result: $integration/success.txt
