platform: linux

image_resource:
  type: docker-image
  source: {repository: praqma/gh-pages}

inputs:
- name: CheckingBranches
- name: ConcourseTest

outputs:
- name: integration

run:
  path: ConcourseTest/ci/scripts/buildtest.sh
