platform: linux

image_resource:
  type: docker-image
  source: {repository: praqma/gh-pages}

inputs:
- name: CheckingBranches
- name: Praqma.com
- name: private_key

outputs:
- name: integration

run:
  path: CheckingBranches/ci/scripts/checkreadybranch.sh
