platform: linux

image_resource:
  type: docker-image
  source: {repository: praqma/gh-pages}

params:
  key_file: /tmp/git-resource-private-key

inputs:
- name: CheckingBranches
- name: Praqma.com
- name: stuff


outputs:
- name: integration

run:
  path: CheckingBranches/ci/scripts/checkreadybranch.sh
  # args: [{{private_key}}]
