platform: linux

image_resource:
  type: docker-image
  source: {repository: praqma/gh-pages}

inputs:
- name: CheckingBranches
  path: tmp/
- name: Praqma.com


outputs:
- name: integration

run:
  path: CheckingBranches/ci/scripts/checkreadybranch.sh
  # args: [{{private_key}}]
