platform: linux

image_resource:
  type: docker-image
  source: {repository: praqma/gh-pages}

inputs:
- name: CheckingBranches
- name: praqma.com

outputs:
- name: integration

run:
  path: CheckingBranches/ci/scripts/buildtest.sh
