platform: linux

image_resource:
  type: docker-image
  source: {repository: thakangbaby/image}

inputs:
- name: repository
outputs:
  - name: integration

run:
  path: ConcourseTest/ci/scripts/integration.sh
