platform: linux

image_resource:
  type: docker-image
  source: {repository: thakangbaby/image}

inputs:
- name: ConcourseTest
outputs:
  - name: integration

run:
  path: ConcourseTest/ci/Script/branch-quest.sh
