platform: linux

image_resource:
  type: docker-image
  source: {repository: thakangbaby/image}

inputs:
- name: CheckingBranches

outputs:
- name: integration

run:
  path: CheckingBranches/ci/scripts/branch-quest.sh
