platform: linux

image_resource:
  type: docker-image
  source: {repository: microsoft/dotnet}

inputs:
- name: repository
outputs:
  - name: integration

run:
  path: repository/integration/branch-quest.sh






